#!/usr/bin/env bash
# Pure Cargo/source/link rejection fixtures for init-neutral-policy.sh.

set -Eeuo pipefail
export LC_ALL=C
umask 077

[[ $# -eq 1 ]] || {
    printf 'usage: init-neutral-policy-tests.sh REPOSITORY_ROOT\n' >&2
    exit 2
}
repo_root=$1
policy="$repo_root/scripts/init-neutral-policy.sh"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/bootart-init-neutral.XXXXXXXXXX")"
cleanup() {
    case "$tmp" in
        "${TMPDIR:-/tmp}"/bootart-init-neutral.*) rm -rf -- "$tmp" ;;
        *) printf 'refusing unsafe init-neutral fixture cleanup: %s\n' "$tmp" >&2 ;;
    esac
}
trap cleanup EXIT HUP INT TERM

new_fixture() {
    local name=$1 root="$tmp/$1"
    mkdir -p -- "$root/src"
    cat >"$root/Cargo.toml" <<'EOF'
[package]
name = "fixture"
version = "0.0.0"
edition = "2024"
build = false
EOF
    cat >"$root/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "fixture"
version = "0.0.0"
EOF
    printf 'fn main() {}\n' >"$root/src/main.rs"
    printf 'check:\n\t@true\n' >"$root/Makefile"
    printf '{}\n' >"$root/flake.nix"
    printf '%s\n' "$root"
}

add_path_package() {
    local root=$1 package=$2
    mkdir -p -- "$root/$package/src"
    cat >"$root/$package/Cargo.toml" <<EOF
[package]
name = "$package"
version = "0.0.0"
edition = "2024"
build = false
EOF
    printf 'pub fn marker() {}\n' >"$root/$package/src/lib.rs"
}

lock_path_package() {
    local root=$1 package=$2
    cat >"$root/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "fixture"
version = "0.0.0"
dependencies = [
 "$package",
]

[[package]]
name = "$package"
version = "0.0.0"
EOF
}

expect_rejected() {
    local root=$1 label=$2
    if bash "$policy" "$root" >/dev/null 2>&1; then
        printf 'init-neutral fixture unexpectedly passed: %s\n' "$label" >&2
        exit 1
    fi
}

fixture="$(new_fixture valid)"
printf '.PHONY: vm-test-uninstall-dracut-systemd\nvm-test-uninstall-dracut-systemd:\n\t@true\n' \
    >>"$fixture/Makefile"
bash "$policy" "$fixture" >/dev/null

fixture="$(new_fixture direct-dependency)"
add_path_package "$fixture" zbus
cat >>"$fixture/Cargo.toml" <<'EOF'

[dependencies]
zbus = { path = "zbus" }
EOF
lock_path_package "$fixture" zbus
expect_rejected "$fixture" direct-dependency

fixture="$(new_fixture renamed-inline-dependency)"
add_path_package "$fixture" zbus
cat >>"$fixture/Cargo.toml" <<'EOF'

[dependencies]
friendly-transport = { package = 'zbus', path = 'zbus' }
EOF
lock_path_package "$fixture" zbus
expect_rejected "$fixture" renamed-inline-dependency

fixture="$(new_fixture dependency-table)"
add_path_package "$fixture" zbus
cat >>"$fixture/Cargo.toml" <<'EOF'

  [dependencies.zbus]
  path = "zbus"
EOF
lock_path_package "$fixture" zbus
expect_rejected "$fixture" dependency-table

for native_package in libsystemd-sys libdbus-sys; do
    fixture="$(new_fixture "native-${native_package}")"
    add_path_package "$fixture" "$native_package"
    cat >>"$fixture/Cargo.toml" <<EOF

[dependencies]
friendly-native = { package = "$native_package", path = "$native_package" }
EOF
    lock_path_package "$fixture" "$native_package"
    expect_rejected "$fixture" "renamed-${native_package}"
done

fixture="$(new_fixture stale-lock)"
add_path_package "$fixture" harmless-helper
cat >>"$fixture/Cargo.toml" <<'EOF'

[dependencies]
harmless-helper = { path = "harmless-helper" }
EOF
lock_path_package "$fixture" harmless-helper
sed -i '0,/version = "0.0.0"/s//version = "0.0.1"/' \
    "$fixture/harmless-helper/Cargo.toml"
expect_rejected "$fixture" stale-lock

fixture="$(new_fixture lock-package)"
cat >>"$fixture/Cargo.lock" <<'EOF'

[[package]]
name = "dbus"
version = "0.0.0"
EOF
expect_rejected "$fixture" lock-package

fixture="$(new_fixture source-api)"
cat >"$fixture/src/main.rs" <<'EOF'
use zbus::Connection;
fn main() { let _ = core::mem::size_of::<Connection>(); }
EOF
expect_rejected "$fixture" source-api

fixture="$(new_fixture native-link-attribute)"
cat >"$fixture/src/main.rs" <<'EOF'
#[link (name = "systemd")]
unsafe extern "C" {}
fn main() {}
EOF
expect_rejected "$fixture" native-link-attribute

fixture="$(new_fixture cargo-link-config)"
mkdir -p -- "$fixture/.cargo"
cat >"$fixture/.cargo/config.toml" <<'EOF'
[build]
rustflags = ["-l", "systemd"]
EOF
expect_rejected "$fixture" cargo-link-config

fixture="$(new_fixture make-link-config)"
printf 'check:\n\t@RUSTFLAGS="-l=systemd" true\n' >"$fixture/Makefile"
expect_rejected "$fixture" make-link-config

printf 'bootart-init-neutral: Cargo/source/link rejection fixtures PASS\n'
