#!/usr/bin/env bash
# Pure rejection fixtures for scripts/source-layout-policy.sh.

set -Eeuo pipefail
export LC_ALL=C
umask 077

[[ $# -eq 1 ]] || {
    printf 'usage: source-layout-policy-tests.sh REPOSITORY_ROOT\n' >&2
    exit 2
}
repo_root=$1
policy="$repo_root/scripts/source-layout-policy.sh"
[[ -f "$policy" && ! -L "$policy" ]] || {
    printf 'source-layout policy is missing or symlinked\n' >&2
    exit 2
}

tmp="$(mktemp -d "${TMPDIR:-/tmp}/bootart-source-layout.XXXXXXXXXX")"
cleanup() {
    case "$tmp" in
        "${TMPDIR:-/tmp}"/bootart-source-layout.*) rm -rf -- "$tmp" ;;
        *) printf 'refusing unsafe fixture cleanup: %s\n' "$tmp" >&2 ;;
    esac
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

new_fixture() {
    local name=$1 root="$tmp/$1"
    mkdir -p -- "$root/src"
    cat >"$root/Cargo.toml" <<'EOF'
[package]
name = "fixture"
version = "0.0.0"
edition = "2024"
autobins = false
autoexamples = false
build = false

[[bin]]
name = "bootart"
path = "src/main.rs"
EOF
    cat >"$root/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "fixture"
version = "0.0.0"
EOF
    printf 'fn main() {}\n' >"$root/src/main.rs"
    printf '%s\n' "$root"
}

expect_rejected() {
    local root=$1 label=$2
    if bash "$policy" "$root" >/dev/null 2>&1; then
        printf 'unsafe source-layout fixture unexpectedly passed: %s\n' "$label" >&2
        exit 1
    fi
}

expect_rejected_with() {
    local root=$1 label=$2 expected=$3 output
    if output="$(bash "$policy" "$root" 2>&1)"; then
        printf 'unsafe source-layout fixture unexpectedly passed: %s\n' "$label" >&2
        exit 1
    fi
    case "$output" in
        *"$expected"*) ;;
        *)
            printf 'source-layout fixture %s failed for the wrong reason; expected diagnostic: %s\n' \
                "$label" "$expected" >&2
            printf '%s\n' "$output" >&2
            exit 1
            ;;
    esac
}

bash "$policy" "$(new_fixture valid)" >/dev/null

fixture="$(new_fixture commented-bin-header)"
mkdir -p -- "$fixture/tools"
printf 'fn main() {}\n' >"$fixture/tools/helper.rs"
cat >>"$fixture/Cargo.toml" <<'EOF'

[[bin]] # a comment must not hide a helper target
name = "helper"
path = "tools/helper.rs"
EOF
expect_rejected "$fixture" commented-bin-header

fixture="$(new_fixture commented-example-header)"
mkdir -p -- "$fixture/examples"
printf 'fn main() {}\n' >"$fixture/examples/demo.rs"
cat >>"$fixture/Cargo.toml" <<'EOF'

[[example]] # a comment must not hide an example target
name = "demo"
path = "examples/demo.rs"
EOF
expect_rejected "$fixture" commented-example-header

fixture="$(new_fixture explicit-custom-build)"
mkdir -p -- "$fixture/tools"
printf 'fn main() {}\n' >"$fixture/tools/generate.rs"
sed -i 's/^build = false$/build = "tools\/generate.rs"/' "$fixture/Cargo.toml"
expect_rejected "$fixture" explicit-custom-build

fixture="$(new_fixture stale-lock)"
mkdir -p -- "$fixture/helper/src"
cat >"$fixture/helper/Cargo.toml" <<'EOF'
[package]
name = "helper"
version = "0.0.0"
edition = "2024"
build = false
EOF
printf 'pub fn helper() {}\n' >"$fixture/helper/src/lib.rs"
cat >>"$fixture/Cargo.toml" <<'EOF'

[dependencies]
helper = { path = "helper" }
EOF
expect_rejected "$fixture" stale-lock

fixture="$(new_fixture hidden-src-bin)"
mkdir -p -- "$fixture/src/bin"
printf 'fn main() {}\n' >"$fixture/src/bin/helper.rs"
expect_rejected "$fixture" hidden-src-bin

fixture="$(new_fixture distribution-installer-module)"
mkdir -p -- "$fixture/src/install"
printf 'pub fn install() {}\n' >"$fixture/src/install/ubuntu.rs"
expect_rejected_with "$fixture" distribution-installer-module \
    'distribution-named product installer module is forbidden'

fixture="$(new_fixture distribution-identity-backend)"
mkdir -p -- "$fixture/src/install"
printf 'pub const REQUIRED_OS: &str = "Fedora";\n' >"$fixture/src/install/dracut_systemd.rs"
expect_rejected_with "$fixture" distribution-identity-backend \
    'distribution identity is forbidden in product installer source'

fixture="$(new_fixture symlinked-main)"
mv -- "$fixture/src/main.rs" "$fixture/main-real.rs"
ln -s -- ../main-real.rs "$fixture/src/main.rs"
expect_rejected "$fixture" symlinked-main

fixture="$(new_fixture path-attribute)"
printf '#[path = "../outside.rs"]\nmod outside;\nfn main() {}\n' >"$fixture/src/main.rs"
printf 'pub fn hidden() {}\n' >"$fixture/outside.rs"
expect_rejected_with "$fixture" path-attribute 'module path attributes are forbidden'

fixture="$(new_fixture multiline-path-attribute)"
cat >"$fixture/src/main.rs" <<'EOF'
#
[
    path
    /* comments are whitespace between Rust tokens */
    =
    "../outside.rs"
]
mod outside;
fn main() {}
EOF
printf 'pub fn hidden() {}\n' >"$fixture/outside.rs"
expect_rejected_with "$fixture" multiline-path-attribute 'module path attributes are forbidden'

fixture="$(new_fixture cfg-attr-path)"
cat >"$fixture/src/main.rs" <<'EOF'
#[cfg_attr(any(), path = "../outside.rs")]
mod outside;
fn main() {}
EOF
printf 'pub fn hidden() {}\n' >"$fixture/outside.rs"
expect_rejected_with "$fixture" cfg-attr-path 'module path attributes are forbidden'

fixture="$(new_fixture multiline-cfg-attr-path)"
cat >"$fixture/src/main.rs" <<'EOF'
#[
    cfg_attr(
        any(),
        path
        /* a comment must not hide the assignment */
        =
        "../outside.rs"
    )
]
mod outside;
fn main() {}
EOF
printf 'pub fn hidden() {}\n' >"$fixture/outside.rs"
expect_rejected_with "$fixture" multiline-cfg-attr-path 'module path attributes are forbidden'

fixture="$(new_fixture cfg-attr-bracket-char-path)"
cat >"$fixture/src/main.rs" <<'EOF'
#[cfg_attr(any(), arbitrary = ']', path = "../outside.rs")]
mod outside;
fn main() {}
EOF
printf 'pub fn hidden() {}\n' >"$fixture/outside.rs"
expect_rejected_with "$fixture" cfg-attr-bracket-char-path 'module path attributes are forbidden'

fixture="$(new_fixture library-outside-src)"
printf 'pub fn exported() {}\n' >"$fixture/product_library.rs"
cat >>"$fixture/Cargo.toml" <<'EOF'

[lib]
path = "product_library.rs"
EOF
expect_rejected_with "$fixture" library-outside-src 'library target source is outside repository src/'

fixture="$(new_fixture symlinked-library-root)"
printf 'pub fn exported() {}\n' >"$fixture/library-real.rs"
ln -s -- library-real.rs "$fixture/product-library.rs"
cat >>"$fixture/Cargo.toml" <<'EOF'

[lib]
path = "product-library.rs"
EOF
expect_rejected_with "$fixture" symlinked-library-root 'library target source must be a regular non-symlink file'

fixture="$(new_fixture attribute-lookalikes)"
cat >"$fixture/src/main.rs" <<'EOF'
// #[cfg_attr(any(), path = "../comment.rs")]
const NORMAL: &str = "#[path = \\\"../string.rs\\\"]";
const RAW: &str = r##"#[cfg_attr(any(), path = "../raw.rs")]"##;
fn main() { let _ = (NORMAL, RAW); }
EOF
bash "$policy" "$fixture" >/dev/null

for vm_fixture_token in 'bootart.vm.gui-password=1' '112358' 'encrypted-drive.qcow2'; do
    fixture="$(new_fixture vm-fixture-token)"
    printf 'const VM_FIXTURE: &str = "%s";\nfn main() { let _ = VM_FIXTURE; }\n' \
        "$vm_fixture_token" > "$fixture/src/main.rs"
    expect_rejected_with "$fixture" vm-fixture-token \
        'VM fixture token is forbidden below src/'
done
unset vm_fixture_token

fixture="$(new_fixture local-path-dependency)"
mkdir -p -- "$fixture/helper/src"
cat >"$fixture/helper/Cargo.toml" <<'EOF'
[package]
name = "helper"
version = "0.0.0"
edition = "2024"
build = false
EOF
printf 'pub fn helper() {}\n' >"$fixture/helper/src/lib.rs"
cat >>"$fixture/Cargo.toml" <<'EOF'

[dependencies]
helper = { path = "helper" }
EOF
cat >"$fixture/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "fixture"
version = "0.0.0"
dependencies = [
 "helper",
]

[[package]]
name = "helper"
version = "0.0.0"
EOF
expect_rejected "$fixture" local-path-dependency

fixture="$(new_fixture extra-library-artifact)"
printf 'pub fn exported() {}\n' >"$fixture/src/lib.rs"
cat >>"$fixture/Cargo.toml" <<'EOF'

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
EOF
expect_rejected "$fixture" extra-library-artifact

for macro in include include_str include_bytes; do
    fixture="$(new_fixture "external-${macro}")"
    printf 'const X: &str = %s!("payload.rs");\nfn main() { let _ = X; }\n' \
        "$macro" >"$fixture/src/main.rs"
    expect_rejected "$fixture" "external-${macro}"
done

fixture="$(new_fixture aliased-include-macro)"
cat >"$fixture/src/main.rs" <<'EOF'
use std::include_str as external_text;
const X: &str = external_text!("payload.txt");
fn main() { let _ = X; }
EOF
expect_rejected "$fixture" aliased-include-macro

printf 'bootart-source-layout: rejection fixtures PASS\n'
